//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Reginstration_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Id { get; set; }
        public string MyTopics { get; set; }
        public string Status { get; set; }
        public string topicCode { get; set; }
        public string createdBy { get; set; }
        public System.DateTime created { get; set; }
        public string modifiedBy { get; set; }
        public System.DateTime modified { get; set; }
    }
}
