//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Reginstration_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Audit
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string SecretId { get; set; }
        public int contact { get; set; }
        public System.DateTime LastLoggedin { get; set; }
        public string createdBy { get; set; }
        public System.DateTime created { get; set; }
    }
}
